mod avoid_mutable_accumulation;
mod consistent_error_handling;
mod descriptive_error_messages;
mod max_positional_params;
mod prefer_builtin_commands;
mod prefer_each_over_for;
mod prefer_error_make;
mod prefer_match_over_if_chain;
mod prefer_parse_command;
mod prefer_range_iteration;

pub use avoid_mutable_accumulation::AvoidMutableAccumulation;
pub use consistent_error_handling::ConsistentErrorHandling;
pub use descriptive_error_messages::DescriptiveErrorMessages;
pub use max_positional_params::MaxPositionalParams;
pub use prefer_builtin_commands::PreferBuiltinCommands;
pub use prefer_each_over_for::PreferEachOverFor;
pub use prefer_error_make::PreferErrorMake;
pub use prefer_match_over_if_chain::PreferMatchOverIfChain;
pub use prefer_parse_command::PreferParseCommand;
pub use prefer_range_iteration::PreferRangeIteration;
