pub mod avoid_mutable_accumulation;
pub mod consistent_error_handling;
pub mod descriptive_error_messages;
mod external_command_helper;
pub mod max_positional_params;
pub mod prefer_builtin_commands;
pub mod prefer_builtin_system_commands;
pub mod prefer_builtin_text_transforms;
pub mod prefer_each_over_for;
pub mod prefer_error_make;
pub mod prefer_match_over_if_chain;
pub mod prefer_parse_command;
pub mod prefer_range_iteration;

pub use avoid_mutable_accumulation::AvoidMutableAccumulation;
pub use consistent_error_handling::ConsistentErrorHandling;
pub use descriptive_error_messages::DescriptiveErrorMessages;
pub use max_positional_params::MaxPositionalParams;
pub use prefer_builtin_commands::PreferBuiltinForCommonCommands;
pub use prefer_builtin_system_commands::PreferBuiltinSystemCommands;
pub use prefer_builtin_text_transforms::PreferBuiltinTextTransforms;
pub use prefer_each_over_for::PreferEachOverFor;
pub use prefer_error_make::PreferErrorMake;
pub use prefer_match_over_if_chain::PreferMatchOverIfChain;
pub use prefer_parse_command::PreferParseCommand;
pub use prefer_range_iteration::PreferRangeIteration;
