# Automatic release workflow for Codeberg
# Triggers on git tags matching v* pattern (e.g., v0.0.118)
#
# Local usage:
#   nu .woodpecker/changelog.nu
#   nu .woodpecker/build.nu
#   nu .woodpecker/release.nu v0.0.119

when:
  - event: tag
    ref: refs/tags/v*

steps:
  - name: changelog
    image: nixos/nix:latest
    commands:
      - nix-shell -p git-cliff nushell git --run "nu .woodpecker/changelog.nu"

  - name: build
    image: nixos/nix:latest
    commands:
      - nix-shell -p nushell --run "nu .woodpecker/build.nu"

  - name: release
    image: nixos/nix:latest
    environment:
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      - nix-shell -p nushell git --run "nu .woodpecker/release.nu $CI_COMMIT_TAG"
    depends_on:
      - changelog
      - build
