mod brace_spacing;
mod completion_function_naming;
mod discourage_bare_ignore;
mod discourage_underscore_commands;
mod kebab_case_commands;
mod pipe_spacing;
mod prefer_compound_assignment;
mod prefer_is_not_empty;
mod screaming_snake_constants;
mod snake_case_variables;
mod unnecessary_mut;
mod unnecessary_variable_before_return;

pub use brace_spacing::BraceSpacing;
pub use completion_function_naming::CompletionFunctionNaming;
pub use discourage_bare_ignore::DiscouragedBareIgnore;
pub use discourage_underscore_commands::DiscourageUnderscoreCommands;
pub use kebab_case_commands::KebabCaseCommands;
pub use pipe_spacing::PipeSpacing;
pub use prefer_compound_assignment::PreferCompoundAssignment;
pub use prefer_is_not_empty::PreferIsNotEmpty;
pub use screaming_snake_constants::ScreamingSnakeConstants;
pub use snake_case_variables::SnakeCaseVariables;
pub use unnecessary_mut::UnnecessaryMut;
pub use unnecessary_variable_before_return::UnnecessaryVariableBeforeReturn;
