name: Scripts run on every push
description: This workflow runs scripts for every push on every branch.

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install correct Rust version
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose

  test:
    name: Run unit and integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install correct Rust version
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --verbose
